### ISSUE TITLE
Skipped song

### ISSUE THREAD

**Issue by lwward** [0x6C77/Grooveshare#3]
```
Skipped song: Choker - Honeyblood [Error tw.p.ffprobe]

/home/flabbyrabbit/grooveshare/lib/trackWatcher.js:70
                self.playing.track,
                            ^
TypeError: Cannot read property 'track' of null
    at /home/flabbyrabbit/grooveshare/lib/trackWatcher.js:70:29
    at ChildProcess.<anonymous> (/home/flabbyrabbit/grooveshare/node_modules/node-ffprobe/lib/ffprobe.js:107:12)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

**Comment by lwward** [comment]
```
Skipped song: Dark Blue - Jack's Mannequin [Error tw.p.ffprobe]

/home/flabbyrabbit/grooveshare/lib/trackWatcher.js:70
                self.playing.track,
                            ^
TypeError: Cannot read property 'track' of null
    at /home/flabbyrabbit/grooveshare/lib/trackWatcher.js:70:29
    at ChildProcess.<anonymous> (/home/flabbyrabbit/grooveshare/node_modules/node-ffprobe/lib/ffprobe.js:107:12)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

**Comment by lwward** [comment]
Doesn't happen on every skip

```
Skipped song: Africa - Toto [Error tw.p.ffprobe]
Playing song: Cossack Rocket Patrol - The Space Cossacks [1:49]
```

**Comment by PMaynard** [comment]
Uploaded the tracks db to, http://port22.co.uk/tracks.db, 

```
$ ls data/music/
1e9db35a-9d3c-40d9-b394-a769d9b5ee4b.mp4  9c0ba2f5-03f0-4f17-a45d-5d549fc96b20.mp3
28375f34-92a4-4cdb-ae42-c397afcc9b89.mp3  a8f75390-8e05-48d0-8d58-1aeb07460cd6.mp3
36b98a9a-486f-4e55-80b9-b7f127f4978f.mp4  a980df85-8bfc-43a3-945a-e0e6c3b97739.mp3
516485d7-dcae-4766-8cc1-9f36c49ca429.mp4  b00f3277-cfda-4df1-b7f7-ddde5ecc7bb5.mp4
5e4db97a-653d-49e8-a755-1b86ff05aacb.mp4  bc69d5eb-2cb1-41a8-acab-b26a9a1e33cf.mp4
60c7bd18-4ca9-456b-8e3b-593324e9a1a0.mp3  e95f478b-b969-47c2-bc15-9a08e43440e5.mp3
640a55e3-8bb5-479c-82ea-08f95349c1ac.mp4  f51990ea-4736-443e-a0fa-91ccda77e02e.mp4
6961bc0d-b3fa-4d42-b6de-b59ea0a55e90.mp4  fd715073-25d5-4905-b9cd-9bdbad3e2dcc.mp3
864051ee-19da-4073-a168-1ed6df84d796.mp4  fdbc0fc9-52be-40ca-ba91-e3cc2b1337f3.mp4
94dead04-f8f9-4e13-8b4d-c1146e7f447a.mp4
```

With tmp fix and this db: 

```
✕ {10:29:12}-[~/code/Grooveshare]-(master)-(12 files, 84K)-[osaka@osakapad: +1]
$ nodejs app.js 
Grooveshare running on 127.0.0.1:8080
Library loaded: 19 tracks
Skipped song: Attero Dominatus - Sabaton [Error tw.p.ffprobe]
Skipped song: 40:1 - Sabaton [Error tw.p.ffprobe]
Skipped song: Attero Dominatus - Sabaton [Error tw.p.ffprobe]
Skipped song: Lisdoonvarna - Christy Moore [Error tw.p.ffprobe]
Skipped song: 40:1 - Sabaton [Error tw.p.ffprobe]
Skipped song: 40:1 - Sabaton [Error tw.p.ffprobe]
New client [1]
Skipped song: Attero Dominatus - Sabaton [Error tw.p.ffprobe]
Skipped song: Ghost Division - Sabaton [Error tw.p.ffprobe]
Skipped song: Attero Dominatus - Sabaton [Error tw.p.ffprobe]
Skipped song: 40:1 - Sabaton [Error tw.p.ffprobe]
Playing song: Artillery - Infected Mushroom [4:32]
New client [2]
```
